### ISSUE TITLE
Many false positives added from newly included blacklist

### ISSUE THREAD

**Issue by peterrakmanyi** [deathbybandaid/piholeparser#102]
Hi,

Many false positives included since commit 313122dcbc2fb7004a41d62174f99555347da462 on Sat Nov 2 01:59:33 UTC 2019.

**Other issues caused by this:**
- **#103**
- **#101** 

The originator is the Mother-of-All-ADBLOCKING list.

    piholeparser-master\MirroredFiles\MirroredBlacklists\Mother-of-All-ADBLOCKING.txt

This seems to include a lot of false positives.

Some, that I've found:

    0.0.0.0 amazon.co.uk
    0.0.0.0 amazon.de
    0.0.0.0 amazon.fr
    0.0.0.0 ebay.co.uk
    0.0.0.0 ebay.fr
    0.0.0.0 ebay.it

Rules are propageted into these lists:

    piholeparser-master\Subscribable-Lists\CombinedBlacklists\CombinedBlackLists.txt
    piholeparser-master\Subscribable-Lists\CombinedBlacklists\DeathbybandaidList.txt
    piholeparser-master\Subscribable-Lists\CountryCodesLists\UnitedKingdom.txt
    piholeparser-master\Subscribable-Lists\ParsedBlacklists\Mother-of-All-ADBLOCKING.txt

I don't know how the rules ended up on that list as it is literally just a shared file without a repo or a documentation. The only info is this thread: https://forum.xda-developers.com/showthread.php?t=1916098

The list is referenced here:

    piholeparser-master\ScriptLsts\Blacklsts\CombinedBlackLsts.lst
    piholeparser-master\ScriptLsts\Blacklsts\MainBlacklsts\Mother-of-All-ADBLOCKING.lst
    piholeparser-master\ScriptLsts\Whitelsts\WhiteDomains\Script.domains
    piholeparser-master\Subscribable-Lists\CombinedWhitelists\CombinedWhiteLists.txt

I already sent a message to the creator of that list, but in the meantime, can you please add a whitelist entry for this and update?

Thanks

edit: Found more legit, high-traffic sites blocked because of this list. At this point I recommend no longer trusting this list and not including it.

edit2: Found the actual commit, where poisoned list was added. Referenced related issues.

**Comment by quorn23** [comment]
This was driving me insane for some time now, finally figured i check the issues here, thanks @peterrakmanyi for the heads up, took a look at that blacklist and it's indeed the culprit for domains i was puzzled, that they wouldn't work, etc. Removed this craplist from my local instance, thanks mate!

**Comment by peterrakmanyi** [comment]
Happy to help @quorn23!
