### ISSUE TITLE
Lists unavailable 

### ISSUE THREAD

**Issue by dxm765** [deathbybandaid/piholeparser#2]
Is this no longer being worked on?

I saw in my recent pihole -g that a few of the lists I had from this repo failed to download and were cached.

**Comment by deathbybandaid** [comment]
can you give me examples?

**Comment by deathbybandaid** [comment]
I will also note, that if a list is parsed, and the file is empty, that it gets deleted,,,,


but since the lists are hosted on github, they should work

**Comment by dxm765** [comment]
Apologies , it looks like it was for : 

https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/parsed/Anti-PopAds.txt

Returns 404: not found

**Comment by deathbybandaid** [comment]
use

https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/parsed/AntiPopAds.txt

instead,,,

It's been awhile,, but I got rid of hyphens from file names.

Sorry about that!
