### ISSUE TITLE
Legit domain blocked 

### ISSUE THREAD

**Issue by HappyGuy22** [deathbybandaid/piholeparser#3]
YouTube.com is blocked in AdguardAnnoyancesFilter.txt

**Comment by deathbybandaid** [comment]
Looks like it is in the original unparsed list. Look under mirroredlists.

All my script does is parses the originals. I don't take things out. It's all automated.

**Comment by HappyGuy22** [comment]
Oh! Ok I will look into that

**Comment by deathbybandaid** [comment]
I'm just now testing a new "preparsing" script that might fix this. I think the lines with youtube.com in them are "commented" the script should now cut the comments, empty lines, and asterisks, before the actual parsing happens.

**Comment by deathbybandaid** [comment]
I also added a feature to remove whitelists easily
