### ISSUE TITLE
During update run network is none functional

### ISSUE THREAD

**Issue by Valiceemo** [deathbybandaid/piholeparser#42]
When the update is run via cron, the internet cannot be accessed returning a dns resolution error

**Comment by deathbybandaid** [comment]
There is nothing in my script that would cause dns issues.

Are you referring to using the allparsedlist in pihole?

If so, dnsmasq takes longer when you are importing large amounts of domains.

**Comment by Valiceemo** [comment]
further input....
each morning the dnsmasq service has stopped after the cronjob has run.
according to the pihole gui memory usage is at 79%
this happens every morning.
I have 'installed' the piholeparser as guided in the readme and added the list `http://pi.hole/lists/1111ALLPARSEDLISTS1111.txt ` in the block lists in pi hole settings

**Comment by Valiceemo** [comment]
for reference:
```
pi@raspberrypi:~ $ sudo service dnsmasq status
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: failed (Result: signal) since Tue 2017-06-20 01:04:05 UTC; 7h ago
  Process: 20502 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 17688 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 17683 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 17680 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 17687 (code=killed, signal=KILL)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

**Comment by deathbybandaid** [comment]
My script doesn't touch dnsmasq.

**Comment by Valiceemo** [comment]
ok. 
but you see the problem...
dnsmasq is running OK
piholeparser runs via cron and netwrok is dead and dnsmasq is no longer running

Could it be a load issue?
timing out?

**Comment by deathbybandaid** [comment]
do you have anything else that runs via cron around the same time?

what hardware are you using, I parse them daily, on a pi3 without issue.

**Comment by Valiceemo** [comment]
im running on a Pi3, totally clean install with pihole only installed

no other cron jobs at all

**Comment by deathbybandaid** [comment]
just for fun, (idk your timezone) but disable the cronjob for the night and see if the problem continues.

On the flipside, I parse the files daily, and upload them.

**Comment by Valiceemo** [comment]
yeah i will do this.
think i will do anther fresh clean install of Jessie Lite, install pi-hole and then your parser. ill disable the cron and see where we are at in the morning.
ill report back tomorrow or friday
cheers

**Comment by deathbybandaid** [comment]
any update on your situation?

**Comment by Valiceemo** [comment]
sorry not as yet.
im taking a slightly different approach with my setup
i have an old pi2 set as a vpn server.
im now looking at installing pi-hole along side it, but not having much luck so far

**Comment by deathbybandaid** [comment]
If it helps check out my piadvanced repo

**Comment by Valiceemo** [comment]
thanks

**Comment by deathbybandaid** [comment]
I'm closing this issue, as it's been a while
