### ISSUE TITLE
Parsing error in ListeARListeFREasyList.txt ?

### ISSUE THREAD

**Issue by EWouters** [deathbybandaid/piholeparser#43]
- There are a few urls ending in a pipe `|` symbol in the [list](https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/parsed/ListeARListeFREasyList.txt). Is this a parsing error?
They actually look more like filenames than urls to me.

- Also a filename in [this](https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/parsed/ListeFR.txt) list: -250x250.gif

- Some domains and comments in brackets in this [list](https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/parsed/MVPSHOSTS.txt) e.g. [Google.Diagnostic][2013-01-02]

- Contains [banner.swf](https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/parsed/PLgeneral.txt)

- Contains [_ads.js and -counter.cgi](https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/parsed/SatterlysAdblockPlusFilters.txt)

**Comment by deathbybandaid** [comment]
I'm still trying to figure out how to remove the file names,,, I was thinking about using sed to delete lines with common file extensions, but idk

a valid FQDN is allowed to have dashes and underscores. all other symbols are invalid

after I have it trim pipes from the front of the line, I'll have sed delete all lines with a pipe

**Comment by deathbybandaid** [comment]
Okay, so I made it so that lines with pipes will get deleted if they are still there after chopping them off the front,,, I just did a test file and had it remove .gif lines. I will try to add a few other common asset file extensions.

**Comment by deathbybandaid** [comment]
As for the brackets,, they should be getting removed, idk why they would be slipping through

**Comment by deathbybandaid** [comment]
sed '/[.gif]$/d; /[.ovh]$/d; /[.htm]$/d; /[.html]$/d; /[.php]$/d; /[.png]$/d; /[.swf]$/d; /[.jpg]$/d; /[.cgi]$/d; /[.js]$/d' $filein $fileout

should fix the file extensions,, let me know if you think I missed a crtical one

**Comment by deathbybandaid** [comment]
/[(]/d; /[)]/d; /[$]/d; /\[\//d; /\]\//d; /[{]/d; /[}]/d

is what I've been using for brackets and parenthesis,, apparently it doesn't work like I thought it did.

**Comment by deathbybandaid** [comment]
I'm doing a manual run of the script,, so far it looks like it is hardcore removing lines because of these adjustments

**Comment by deathbybandaid** [comment]
I abruptly stopped the script to add 

sed '/[][)(}{]/d'

which should remove lines with brackets better

**Comment by deathbybandaid** [comment]
apparently down to 1.6 million domains after these adjustments,,, I will need to investigate why there is such a big difference.

I removed all parsed and mirrored lists, so that I can give all the lists a fresh start.

**Comment by deathbybandaid** [comment]
did alot more tweaking and I believe I've resolved this issue
