### ISSUE TITLE
imgur.com Shouldn't be there in any of the EasyPrivacyEasyList and it's possible variants

### ISSUE THREAD

**Issue by TheAntimist** [deathbybandaid/piholeparser#5]
So, this is weird but the parsing is going wrong somewhere, because the full domain imgur.com is blocked which seems to be from EasyPrivacyEasylist, but could quite possibly be from other Easylist variants.

Pretty sure this didn't happen before, could be a Easylist thing, I can't say.

**Comment by deathbybandaid** [comment]
Yeah, I don't actually do anything other than run them through the script

**Comment by TheAntimist** [comment]
Okay, so I checked it right now, with the `parser.pl` and it seems to not have the `imgur.com` domain. Though, looking at your parser code, I notice you have 3 more additions there, could you check that up.

**Comment by deathbybandaid** [comment]
There are three main ways to parse a list, right now I am working on separating the lists into categories.

I'm also looking at implementing a tool to remove domains that users request.

**Comment by deathbybandaid** [comment]
implemented a requested domains feature
