### ISSUE TITLE
Parsed Lists Errors (Missing)

### ISSUE THREAD

**Issue by Omnija** [deathbybandaid/piholeparser#50]
It seems to happen frequently that the parsed lists are being removed. 
Not sure if this is on purposes but it's hard to know whether the list has been removed permanently or temporarily.

**Comment by deathbybandaid** [comment]
I recently changed a great deal of the way the parser processes, and I gave the parsed directory a "clean slate" so that the ALLPARSEDLIST doesn't end up with bad entries,

I also changed it so that the parsed file will not be deleted if there is no update to it.

**Comment by Omnija** [comment]
That's great to hear, have those changes been made currently or will be soon implemented?

**Comment by deathbybandaid** [comment]
already made,,, 

I've been making changes directly on the live branch,,,

the way my script works, I was having trouble testing it with a dev branch,,, and I even tried having a test repo. 

Most of the kinks are worked out now,, but it has a small way to go to be perfect
