### ISSUE TITLE
Cluttered README

### ISSUE THREAD

**Issue by InnovativeInventor** [deathbybandaid/piholeparser#68]
I think this project is awesome. It combines so many blacklists to create a comprehensive ad blocking list. Unfortunately, when I was reading the README, I found it to be rather confusing and hard to navigate. Maybe it could be split up into separate files with the stats placed somewhere else?

**Comment by deathbybandaid** [comment]
The script is still in an "active development state"

I have some major additions and changes on the horizon, and for now, the stats help me visualize the information at-a-glance.

I like the stats being there, and that is probably going to stay. However, I'll take any suggestions regarding the rest of the main README.md
