### ISSUE TITLE
US CERT blocked

### ISSUE THREAD

**Issue by InnovativeInventor** [deathbybandaid/piholeparser#69]
For some reason, https://www.us-cert.gov/ is blocked by the blacklist. Could this be added to the whitelist? I think all government websites should be whitelisted (.gov, .fed, and .mil) automatically. It's extremely unlikely that malware, ads, or other unwanted items will be hosted on one of those TLDs.

Edit (I forgot to say what us-cert is for):
US-CERT is the United States Computer Emergency Readiness Team and gives out alerts about new cyber security threats and helps to protect us government systems (which is the opposite of malware).

**Comment by deathbybandaid** [comment]
I'll have to do some analysis on .gov pages blocked,,, according to the last run of of script
(Working on formatting this log page better)
https://github.com/deathbybandaid/piholeparser/blob/master/RecentRunLogs/TopLevelScripts/EndtaskScripts/65-Calculating-TLD-Percentages.md

it looks like .gov is about 1% of the grand total

I'll add www.us-cert.gov to the whitelist file,,, I'll have to put some thought into implementing a wildcard whitelist feature.

**Comment by deathbybandaid** [comment]
also adding

us-cert.gov

**Comment by deathbybandaid** [comment]
Searching for us-cert

Found In EasyList-Lithuania. Matching Included:
cdn.us-cert.gov
us-cert.gov
www.us-cert.gov

Found In EladKarako. Matching Included:
cdn.us-cert.gov
us-cert.gov
www.us-cert.gov
