### ISSUE TITLE
Master Whitelist

### ISSUE THREAD

**Issue by InnovativeInventor** [deathbybandaid/piholeparser#71]
I think all domains that we whitelist be added to a master list. This would probably be helpful for me and others to look at. I'm not sure if you already have one, but I couldn't find it.

**Comment by deathbybandaid** [comment]
https://github.com/deathbybandaid/piholeparser/blob/master/ScriptLsts/Whitelsts/WhiteDomains/UserSubmitted.domains

**Comment by deathbybandaid** [comment]
I add them to this list, which gets filtered out from the deathbybandaid list at the end
