### ISSUE TITLE
Cloudflare blocked

### ISSUE THREAD

**Issue by InnovativeInventor** [deathbybandaid/piholeparser#73]
cloudflare.com is blocked. Cloudflare is a CDN that helps protect against DDOS attacks

**Comment by deathbybandaid** [comment]
Searching for cloudflare.com

Found In ABP-Japanese-Filters. Matching Included:
ajax.cloudflare.com

Found In EasyList-Lithuania. Matching Included:
cloudflare.com
cloudflare.com.cdn.cloudflare.net
track.cloudflare.com
www.cloudflare.com.cdn.cloudflare.net

Found In EladKarako. Matching Included:
cloudflare.com
cloudflare.com.cdn.cloudflare.net
track.cloudflare.com
www.cloudflare.com.cdn.cloudflare.net

Found In KowabitBOD. Matching Included:
cdnjs.cloudflare.com

Found In Notracking-hostnames. Matching Included:
ajax.cloudflare.com

Found In Thoughtconverge-AdBlock-Filters. Matching Included:
ajax.cloudflare.com

**Comment by deathbybandaid** [comment]
adding it to the whitelist
