### ISSUE TITLE
Feedly.com blocked

### ISSUE THREAD

**Issue by benjaminshell** [deathbybandaid/piholeparser#75]
Feedly.com is being blocked, which is unnecessary. Its ad subdomain (ads.feedly.com) can remain blocked, though.

**Comment by deathbybandaid** [comment]
Searching for feedly.com

Found In EasyList-Lithuania. Matching Included:
feedly.com
www.feedly.com

Found In EladKarako. Matching Included:
feedly.com
www.feedly.com

**Comment by deathbybandaid** [comment]
I added it to the whitelist, along with the www version
