### ISSUE TITLE
piholeparser not working

### ISSUE THREAD

**Issue by HellboyPI** [deathbybandaid/piholeparser#76]
Hello! Is your piholeparser still active? The blacklists are not created. The log on Github shows:
" Script Took 0 Minutes To Filter 0 Lists. See Log Here. The Edited AllParsed File is 0 MB And Contains 10 Domains."

**Comment by deathbybandaid** [comment]
I'll take a look tomorrow, it all runs automatically

**Comment by deathbybandaid** [comment]
This fixed it.
