### ISSUE TITLE
Adguard lists broken?

### ISSUE THREAD

**Issue by pbalthasar** [deathbybandaid/piholeparser#77]
All the parsed lists from AdGuard only contain a single item and almost every list is stored in "BlacklstsThatDie" which seems not right as the original lists contain several hundred items?

https://github.com/AdguardTeam/AdguardFilters

**Comment by deathbybandaid** [comment]
I'll run my fresh start script,, maybe this was an accident.

**Comment by pbalthasar** [comment]
Nothing changed?
All AdGuardLists still are in https://github.com/deathbybandaid/piholeparser/tree/master/ScriptLsts/Blacklsts/BlacklstsThatDie and contain just a single item.

**Comment by deathbybandaid** [comment]
I haven't had time to look into this further.

I'll try to glance at the parsing logs


https://github.com/deathbybandaid/piholeparser/blob/master/RecentRunLogs/TopLevelScripts/30-Processing-Blacklists.md

**Comment by pbalthasar** [comment]
I see. All of them are killed when "Removing Invalid FQDN Characters". Adguard-Mobile-Ads goes down from 1762 to 3 lines in this step.

**Comment by pbalthasar** [comment]
It hasn't changed since?
