### ISSUE TITLE
Domains to be whitelisted 

### ISSUE THREAD

**Issue by KnightTim** [deathbybandaid/piholeparser#78]
There seems to be a high number of false positives in some of the lists parsed. 

These are the ones I have found so far: 
tiny.cc - URL shortener 
disqus.com - commonly used to host comment sections 
www.lightinthebox.com - shopping/deal site
redirector.gvt1.com - needed for firefox updates 
pinterest.com - social network / bookmark site 
www.pinterest.com - ^
fpdownload.adobe.com - needed to watch ESPN or download updates for adobe software. 
amzn.to - shortened URL for amazon products 
t.co - shortened URLs on twitter
ow.ly - URL shortener 
bit.ly - URL shortener 
j.mp - URL shortener 
lego.com - awesome toys 
shop.lego.com - place to buy said toys 
boardgamegeek.com - site centered around the hobby of board gaming
target.com - Shopping site 
live.com - MS Outlook email 
donorschoose.org - Website for helping teachers 
hulu.com - streaming service 
rover.ebay.com - used to sign into ebay

I can understand blocking the following domains but wanted to point them out. 
These following domains prevent facebook chat:
0-edge-chat.facebook.com
1-edge-chat.facebook.com
2-edge-chat.facebook.com
3-edge-chat.facebook.com
4-edge-chat.facebook.com
5-edge-chat.facebook.com
6-edge-chat.facebook.com
edge-chat.facebook.com

This prevents downloading your data from facebook: 
bigzipfiles.facebook.com 

If I find more, I can make additional issues or just comment on this one, whichever you prefer?
Thanks for all the work you do.

**Comment by deathbybandaid** [comment]
added them to the whitelist, doing a fresh run now

if they are still in the big list afterwards, then I will look at the whitelist script to see what is breaking things

**Comment by deathbybandaid** [comment]
I can't seem to find the issue

````
Compiling Edited Combined List Fri Apr 27 18:21:38 UTC 2018

Generating All Parsed List (edited).

Adding Blacklist Domains.
2779731 lines after blacklist

Removing whitelist Domains.
2779698 lines after whitelist

Removing Duplicates.
2779690 lines after deduping

Size of  = 61 MB.
2779690 Lines After Compiling.
Big List Edited Created Successfully.

````

Based on the number dropping, it looks like the domains are being taken out,,, but when I check for  bigzipfiles.facebook.com it is still there

**Comment by deathbybandaid** [comment]
attempting to run 2 different ways of removing the whitelist entries, yields the same result

**Comment by deathbybandaid** [comment]
going to make a devbranch for testing purposes (rally should have do than ages ago)

**Comment by deathbybandaid** [comment]
I'm going to push some nice changes to the scripting in master, but I still haven't found what is wrong with the whitelist

using the same technique on a smaller file seems to work without issue,,,,

**Comment by KnightTim** [comment]
Found another couple domains 

Windows tool for cleaning the system: 
www.ccleaner.com
ccleaner.com 

I grabbed the repo, but I'm on a Windows system and the query list tool gave me an error about vars, and I don't really have time to look into right now.  Thanks.

**Comment by deathbybandaid** [comment]
I've never run the tool on windows, I doubt it would work
