### ISSUE TITLE
Another blacklist source

### ISSUE THREAD

**Issue by InnovativeInventor** [deathbybandaid/piholeparser#86]
http://malc0de.com/bl/ from https://security.stackexchange.com/questions/32058/looking-for-url-blacklists-of-malicious-websites

**Comment by InnovativeInventor** [comment]
@deathbybandaid why was this closed?

**Comment by deathbybandaid** [comment]
Malcode list has been included for years

**Comment by deathbybandaid** [comment]
https://github.com/deathbybandaid/piholeparser/blob/master/ScriptLsts/Blacklsts/MainBlacklsts/malc0de.list
