### ISSUE TITLE
8 of the 14 lists in "Lists That Do NOT use https." do in fact use HTTPS nowadays

### ISSUE THREAD

**Issue by DandelionSprout** [deathbybandaid/piholeparser#91]
Going by the recentmost available links on FilterLists.com, the following 8 lists from *[Lists That Do NOT use https](https://github.com/deathbybandaid/piholeparser/blob/master/RecentRunLogs/TopLevelScripts/10-Running-Initial-Tasks/20-Identifying-Lists-Without-https.md#lists-that-do-not-use-https)* have obtained HTTPS in recent years:

* DNS-BH-Malware-Domains
* Dan-Pollocks-Hosts
* Disconnect-Malvertising-Filter
* JapaneseSiteAdblockFilterver2
* JoeWein
* PLgeneral
* The-Hosts-File-Project
* Tofu-Filter

I presume that this means that their corresponding links in e.g. https://github.com/deathbybandaid/piholeparser/tree/master/ScriptLsts/Blacklsts/MainBlacklsts should be updated to their HTTPS links.

**Comment by deathbybandaid** [comment]
updating those now, thanks!
