### ISSUE TITLE
Create seperate combined blacklist w/ porn sites

### ISSUE THREAD

**Issue by cagapisto** [deathbybandaid/piholeparser#96]
Is it possible to create a separate branch of the community driven combined blacklist that excludes porn sites. Maybe it would just be enough to exclude the following parsed blacklists in it (the ones I could find, which clearly state their porn blocking):

- Chad-Mayfield-Porn-Blocklist-Heavy.txt
- Chad-Mayfield-Porn-Blocklist-Light.txt
- Steven-Blacks-Porn.txt

I personally block them anyway, but due to the fact that I deploy my Pi-Hole for a bunch of people, it would be nice to give them the freedom of choice to decide whether they like to view porn or not. And I don't want to fill my hole whitelist with these three blocklists.

**Comment by deathbybandaid** [comment]
running a test now, but theoretically, if the list name contains "porn" it will filter out into a new list
